http {
    server {
        listen               127.0.0.1:8080;
        client_max_body_size 10M;

        error_page 400 /errors/400.html;
        error_page 403 /errors/403.html;
        error_page 404 /errors/404.html;
        error_page 405 /errors/405.html;
        error_page 500 /errors/500.html;

        # basic static serving
        location / {
            methods   GET POST DELETE;
            root      /var/www/html;
            index     index.html;
            autoindex off;
        }

        # directory listing enabled
        location /files {
            methods   GET;
            root      /var/www/files;
            autoindex on;
        }

        # file upload
        location /upload {
            methods      POST DELETE;
            upload_store /var/www/uploads;
        }

        # http redirect
        location /old {
            return 301 /new;
        }

        # cgi
        location /cgi-bin {
            methods  GET POST;
            root     /var/www/cgi-bin;
            cgi_pass .py;
        }
    }
}
