http {
    server {
        listen               127.0.0.1:8080;
        client_max_body_size 10M;

        location / {
            methods   GET POST DELETE;
            root      /home/msafa/Core/WebServe/www/html;
            index     index.html;
            autoindex off;
        }

        location /files {
            methods   GET POST DELETE;
            root      /home/msafa/Core/WebServe/www/files;
            autoindex on;
        }
    }
}
