#!/usr/bin/env python3
# Minimal CGI script: prints a CGI header block followed by an HTML body.
# The server pipes our stdout back to the client.

import sys

body = """<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>CGI hello</title></head>
<body>
  <h1>Hello from Python CGI 🐍</h1>
  <p>This page was generated by executing www/test/cgi-bin/hello.py.</p>
  <p><a href="/">back home</a></p>
</body>
</html>
"""

sys.stdout.write("Content-Type: text/html\r\n")
sys.stdout.write("Content-Length: %d\r\n" % len(body.encode("utf-8")))
sys.stdout.write("\r\n")
sys.stdout.write(body)
